### ISSUE TITLE
ide internal fatal error:NullPointerException

### ISSUE THREAD

**Issue by qiu1992** [kgmyshin/eventbus-intellij-plugin#3] opened 2015-06-15 07:32 UTC
I found it on android studio,the version is 1.1.when i use it , an internal error was occur.
the detail info:

null
java.lang.NullPointerException
    at com.kgmyshin.ideaplugin.eventbus.SenderFilter.shouldShow(SenderFilter.java:43)
    at com.kgmyshin.ideaplugin.eventbus.ShowUsagesAction$10.process(ShowUsagesAction.java:381)
    at com.kgmyshin.ideaplugin.eventbus.ShowUsagesAction$10.process(ShowUsagesAction.java:376)
    at com.intellij.find.findUsages.FindUsagesManager$2$2.process(FindUsagesManager.java:358)
    at com.intellij.find.findUsages.FindUsagesManager$2$2.process(FindUsagesManager.java:349)
    at com.intellij.util.CommonProcessors$UniqueProcessor.process(CommonProcessors.java:120)
    at com.intellij.find.findUsages.FindUsagesManager$2$4.process(FindUsagesManager.java:404)
    at com.intellij.find.findUsages.FindUsagesManager$2$4.process(FindUsagesManager.java:394)
    at com.intellij.psi.impl.search.MethodTextOccurrenceProcessor.processReference(MethodTextOccurrenceProcessor.java:64)
    at com.intellij.psi.impl.search.MethodTextOccurrenceProcessor.processTextOccurrence(MethodTextOccurrenceProcessor.java:47)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$17.execute(PsiSearchHelperImpl.java:765)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.processTreeUp(LowLevelSearchUtil.java:126)
    at com.intellij.psi.impl.search.LowLevelSearchUtil.processElementsContainingWordInElement(LowLevelSearchUtil.java:200)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$3$1.compute(PsiSearchHelperImpl.java:214)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$3$1.compute(PsiSearchHelperImpl.java:211)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:890)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.process(PsiSearchHelperImpl.java:211)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$3.process(PsiSearchHelperImpl.java:208)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$16.process(PsiSearchHelperImpl.java:729)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$16.process(PsiSearchHelperImpl.java:723)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$7.compute(PsiSearchHelperImpl.java:371)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$7.compute(PsiSearchHelperImpl.java:356)
    at com.intellij.openapi.application.ex.ApplicationUtil$1.run(ApplicationUtil.java:37)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1104)
    at com.intellij.openapi.application.ex.ApplicationUtil.tryRunReadAction(ApplicationUtil.java:34)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.processVirtualFile(PsiSearchHelperImpl.java:356)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl.access$000(PsiSearchHelperImpl.java:68)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$4.process(PsiSearchHelperImpl.java:304)
    at com.intellij.psi.impl.search.PsiSearchHelperImpl$4.process(PsiSearchHelperImpl.java:299)
    at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:122)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:449)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:106)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by kgmyshin** [comment] 2015-06-15 09:07
Thank you.
I try to investigate the cause.

**Comment by kgmyshin** [comment] 2015-06-16 14:59
This issue was fixed.
And I released 1.2 that is fix version.
So I close this.

**Closed as completed by kgmyshin** 2015-06-16 15:00 UTC

**Comment by qiu1992** [comment] 2015-06-19 01:12
Thank you !
 I have seen the update just now.
![qq 20150619090635](https://cloud.githubusercontent.com/assets/7507384/8245610/3db8ab9e-1663-11e5-8c01-d62517fdd0d3.png)
